[package]
name = "logss"
version = "1.0.0-beta"
authors = ["Victor Rosales <todoesverso@gmail.com>"]
edition = "2018"
publish = false
repository = "https://github.com/todoesverso/logss"
keywords = ["terminal", "logs", "cli", "split"]
categories = ["visualization", "command-line-utilities", "parsing"]
license = "MIT"

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
crossterm = "0.25.0"
is-terminal = "0.4.2"
unicode-width = "0.1.10"
use = "0.0.0"

[dependencies.tui]
version = "0.19.0"
default-features = false
features = ["crossterm"]
