[package]
name = "logss"
version = "1.1.0-alpha"
authors = ["Victor Rosales <todoesverso@gmail.com>"]
edition = "2018"
publish = false
repository = "https://github.com/todoesverso/logss"
keywords = ["terminal", "logs", "cli", "split"]
categories = ["visualization", "command-line-utilities", "parsing"]
license = "MIT"

[dependencies]
crossterm = "0.25.0"
is-terminal = "0.4.2"
unicode-width = "0.1.10"
pico-args = "0.5.0"
ratatui = "0.20.1"
regex = "1.7.3"
serde_yaml = "0.9.19"
serde = {version = "1.0.159", features = ["derive"]}

[profile.release]
codegen-units = 1
lto = "fat"
